# Generated by Django 5.1.2 on 2024-10-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('temp_threshold', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherdata')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.useralertconfig')),
            ],
        ),
    ]
