# Generated by Django 5.1.2 on 2024-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertconfig',
            name='city',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
